name: Deploy to Azure

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Azure CLI
        uses: Azure/setup-azure@v1

      - name: Log in to Azure
        uses: Azure/login@v1
        with:
          client-id: ${{ secrets.AZURE_CLIENT_ID }}
          client-secret: ${{ secrets.AZURE_CLIENT_SECRET }}
          tenant-id: ${{ secrets.AZURE_TENANT_ID }}

      - name: Create Azure resource group
        run: |
          az group create --name bicep1 --location "Canada Central"

      - name: Deploy Bicep template
        run: |
          az deployment group create \
            --resource-group bicep1 \
            --template-file webapp-docker-moduler/main.bicep \
            --parameters @webapp-docker-moduler/parameter.json
